"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const whatsapp = "https://wa.me/40750402452?text=Hello%20AUMOREX%2C%20I%E2%80%99d%20like%20a%20quote%20for%20transporting%20my%20car.";
type Lang = "en" | "de";

export function Header({ lang = "en", active = "" }: { lang?: Lang; active?: string }) {
  const de = lang === "de";
  const root = de ? "/de" : "";
  return <header className="site-header">
    <Link className="brand" href={root || "/"} aria-label="AUMOREX transport home"><span className="brand-mark" aria-hidden="true"><span /><span /></span><span><strong>AUMOREX</strong><small>transport</small></span></Link>
    <button className="menu-toggle" aria-expanded="false" aria-controls="site-nav">{de ? "Menü" : "Menu"}</button>
    <nav id="site-nav" className="site-nav" aria-label="Primary navigation"><a href={`${root || "/"}#service`}>Service</a><a href={`${root || "/"}#routes`}>{de ? "Routen" : "Routes"}</a><Link className={active === "portfolio" ? "active" : ""} href={`${root}/portfolio`}>Portfolio</Link><a href={`${root || "/"}#about`}>{de ? "Über uns" : "About"}</a><Link className={`nav-cta ${active === "quote" ? "active" : ""}`} href={`${root}/quote`}>{de ? "Angebot anfragen" : "Get a quote"}</Link><span className="language"><Link className={!de ? "active" : ""} href={active === "portfolio" ? "/portfolio" : active === "quote" ? "/quote" : "/"}>EN</Link><span>/</span><Link className={de ? "active" : ""} href={active === "portfolio" ? "/de/portfolio" : active === "quote" ? "/de/quote" : "/de"}>DE</Link></span></nav>
  </header>;
}

export function Footer({ lang = "en" }: { lang?: Lang }) { const de = lang === "de"; const root = de ? "/de" : ""; return <footer className="site-footer"><div className="footer-brand"><span className="brand-mark small" aria-hidden="true"><span /><span /></span><strong>AUMOREX</strong><small>transport</small></div><div className="footer-links"><Link href={`${root}/quote`}>{de ? "Angebot" : "Get a quote"}</Link><Link href={`${root}/portfolio`}>Portfolio</Link><Link href={de ? "/de" : "/legal"}>{de ? "Rechtliche Hinweise" : "Legal information"}</Link></div><div className="footer-meta"><span>{de ? "Dedizierter Autotransport in Westeuropa." : "Dedicated car transport across Western Europe."}</span><span>© AUMOREX transport</span></div></footer>; }

export function SiteShell({ children }: { children: React.ReactNode }) {
  const [top, setTop] = useState(false);
  useEffect(() => { const nav = document.querySelector<HTMLElement>(".site-nav"), toggle = document.querySelector<HTMLButtonElement>(".menu-toggle"), header = document.querySelector<HTMLElement>(".site-header"); const scroll = () => { setTop(scrollY > 420); header?.classList.toggle("is-scrolled", scrollY > 24); }; const click = () => { const open = toggle?.getAttribute("aria-expanded") === "true"; toggle?.setAttribute("aria-expanded", String(!open)); nav?.classList.toggle("open", !open); }; toggle?.addEventListener("click", click); addEventListener("scroll", scroll, { passive: true }); scroll(); const route = document.querySelector<HTMLElement>(".routes-section"); const observer = route && "IntersectionObserver" in window ? new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { route.classList.add("is-visible"); observer?.disconnect(); } }, { threshold: .35 }) : null; if (route && observer) observer.observe(route); return () => { toggle?.removeEventListener("click", click); removeEventListener("scroll", scroll); observer?.disconnect(); }; }, []);
  return <>{children}<button className={`back-to-top ${top ? "is-visible" : ""}`} type="button" aria-label="Back to top" onClick={() => scrollTo({ top: 0, behavior: "smooth" })}><span aria-hidden="true">↑</span><span>Back up</span></button></>;
}

const copy = { en: { hero: ["Dedicated car transport", "Dedicated car transport.", "Door to door."], intro: "Fast, dedicated vehicle transport across Western Europe. Based in Romania, we operate our own fleet and work with a network of transport partners, with a focus on Ireland, the UK, France, Spain and Portugal.", response: "We respond to enquiries within 3 hours, 24/7.", service: "The service", serviceTitle: "One car. Dedicated transport.", routes: "The routes", routeTitle: "Focused on the", routeWord: "west.", about: "The people", quote: "Tell us what needs moving." }, de: { hero: ["Dedizierter Autotransport", "Dedizierter Autotransport.", "Tür zu Tür."], intro: "Schneller, dedizierter Fahrzeugtransport in Westeuropa. Von Rumänien aus arbeiten wir mit unserer eigenen Flotte und einem Netzwerk von Transportpartnern — mit Fokus auf Irland, Großbritannien, Frankreich, Spanien und Portugal.", response: "Wir antworten rund um die Uhr innerhalb von 3 Stunden.", service: "Der Service", serviceTitle: "Ein Fahrzeug. Dedizierter Transport.", routes: "Die Routen", routeTitle: "Fokus auf", routeWord: "den Westen.", about: "Die Menschen", quote: "Was soll transportiert werden?" } };

export function HomePage({ lang = "en" }: { lang?: Lang }) {
  const de = lang === "de", c = copy[lang], root = de ? "/de" : "";
  const routes = de ? ["Irland", "Großbritannien", "Frankreich", "Spanien", "Portugal"] : ["Ireland", "United Kingdom", "France", "Spain", "Portugal"];
  return <SiteShell><div className="homepage"><Header lang={lang} /><main>
    <section className="hero section-dark"><div className="hero-copy"><p className="eyebrow">{c.hero[0]}</p><h1>{c.hero[1]}<br /><em>{c.hero[2]}</em></h1><p className="hero-intro">{c.intro}</p><div className="actions"><Link className="button button-light" href={`${root}/quote`}>{de ? "Angebot anfragen" : "Get a quote"} <span>↗</span></Link><a className="text-link light" href={whatsapp} target="_blank" rel="noreferrer">{de ? "WhatsApp schreiben" : "Chat on WhatsApp"} <span>↗</span></a></div><p className="response-note"><span className="pulse" /> {c.response}</p></div><div className="hero-visual"><span className="visual-coordinate">{de ? "RO — WESTEUROPA" : "RO — WESTERN EUROPE"}</span></div></section>
    <section className="facts section-light"><div className="fact"><strong>01</strong><span>{de ? "Ein Fahrzeug, dediziert" : "Single-car transport"}</span></div><div className="fact"><strong>02</strong><span>{de ? "Tür-zu-Tür-Service" : "Door-to-door service"}</span></div><div className="fact"><strong>03</strong><span>{de ? "Routen in Westeuropa" : "Western European routes"}</span></div></section>
    <section id="service" className="split-section section-light"><div className="section-label">{c.service}</div><div className="section-content"><h2>{c.serviceTitle}</h2><p className="large-copy">{de ? "Ihr Fahrzeug reist auf einem offenen Transporter für ein einzelnes Fahrzeug. Abholung und Lieferung werden nach Ihren Anforderungen abgestimmt." : "Your vehicle travels on a single-car open transporter, with collection and delivery arranged around your requirements."}</p><p>{de ? "Nennen Sie uns Route, Fahrzeug und Wunschtermin. Wir besprechen die verfügbaren Optionen direkt mit Ihnen." : "Tell us the route, vehicle and preferred date, and we’ll confirm the available options directly with you."}</p><div className="service-columns"><div><h3>{de ? "Fahrzeuganforderungen" : "Vehicle requirements"}</h3><p>{de ? "Unser Standardservice umfasst Fahrzeuge bis 2.200 kg. Fahrzeuge bis 2.500 kg können gegen Aufpreis und nach Bestätigung möglich sein." : "Our standard service accommodates vehicles weighing up to 2,200 kg. Vehicles up to 2,500 kg may be considered at an additional charge, subject to confirmation."}</p></div><div><h3>{de ? "Fahrzeuge ohne Funktion" : "Non-running vehicles"}</h3><p>{de ? "Komplett fahruntüchtige Fahrzeuge können für die Verladung mit einer Seilwinde geprüft werden. Die Eignung wird im Einzelfall bestätigt." : "Complete non-running vehicles can also be considered for winch loading. Suitability is confirmed case by case."}</p></div></div></div></section>
    <section id="routes" className="routes-section section-copper"><div className="section-label">{c.routes}</div><div className="routes-content"><h2>{c.routeTitle}<br /><em className="route-word">{c.routeWord}</em></h2><p>{de ? "Unser Hauptkorridor verbindet Irland, Großbritannien, Frankreich, Spanien und Portugal. Andere europäische Ziele sind auf Anfrage möglich." : "Our principal corridor connects Ireland, the UK, France, Spain and Portugal. Other European destinations are possible on enquiry."}</p><div className="route-list">{routes.map((r) => <span key={r}>{r}</span>)}<span>{de ? "Übriges Europa" : "Other Europe"} <small>{de ? "auf Anfrage" : "on enquiry"}</small></span></div></div></section>
    <section className="proof-section section-light"><div className="section-label">{de ? "Transportgeschichten" : "Transport stories"}</div><div className="proof-content"><h2>{de ? "Echte Arbeit. Sorgfältig ausgeführt." : "Real work, carefully handled."}</h2><p>{de ? "Wir bauen ein Portfolio echter Transporte auf, mit Fotos und Falldetails, die unter Berücksichtigung von Veröffentlichungsrechten und Kundendiskretion ausgewählt werden." : "We are building a portfolio of actual transport work, with photography and case details selected for publication rights and client discretion."}</p><Link className="text-link" href={`${root}/portfolio`}>{de ? "Portfolio ansehen" : "View portfolio"} <span>↗</span></Link><div className="proof-note"><strong>{de ? "Bis bestätigte Kundenstimmen verfügbar sind" : "Until approved testimonials are available"}</strong><span>{de ? "zeigen wir die Menschen, Routen und Abläufe hinter jedem Auftrag — niemals erfundene Zitate oder Bewertungen." : "we show the people, routes and process behind each job — never invented quotes or ratings."}</span></div></div></section>
    <section id="about" className="about-section section-dark"><div className="section-label">{c.about}</div><div className="about-content"><h2>{de ? <>Erfahrung am Steuer.<br /><em>Sorgfalt auf der ganzen Strecke.</em></> : <>Experience behind the wheel.<br /><em>Care throughout the journey.</em></>}</h2><p className="large-copy">{de ? "Unser Hauptfahrer bringt mehr als 25 Jahre Erfahrung im Transport mit. Wir verbinden praktische Routenkenntnis mit sorgfältiger Aufmerksamkeit für Transportdokumente und die Details jedes Auftrags." : "Our principal driver brings more than 25 years of transport experience. We combine practical route knowledge with careful attention to transport documentation and the details of each job."}</p></div></section>
    <section className="process-section section-light"><div className="section-label">{de ? "So funktioniert es" : "How it works"}</div><div className="process-list">{(de ? [["Anfrage", "Fahrzeug, Abhol- und Lieferort sowie Wunschtermin mitteilen."], ["Bestätigung", "Wir besprechen Ihre Anforderungen und bestätigen die verfügbaren Optionen."], ["Transport", "Abholung und Lieferung werden nach den bestätigten Auftragsdetails abgestimmt."]] : [["Request", "Share the vehicle, collection and delivery locations, and your preferred collection date."], ["Confirm", "We discuss your requirements directly and confirm the available options."], ["Move", "Collection and delivery are arranged around the confirmed job details."]]).map(([title, text]) => <div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section className="faq-section section-warm"><div className="section-label">{de ? "Fragen" : "Questions"}</div><div className="faq-content"><h2>{de ? "Vor Ihrer Angebotsanfrage." : "Before you request a quote."}</h2>{(de ? [["Welche Informationen benötigen Sie?", "Name, Telefonnummer, E-Mail, Fahrzeug, Abhol- und Lieferort sowie der gewünschte Abholtermin."], ["Ist der Wunschtermin eine Buchung?", "Nein. Es handelt sich um einen gewünschten Abholtermin zur Abstimmung, nicht um eine Reservierung."], ["Gibt es eine feste Lieferzeit?", "Transportoptionen und Zeitplanung werden für jeden Auftrag direkt bestätigt."], ["Können Sie ein nicht fahrbereites Fahrzeug transportieren?", "Komplett fahruntüchtige Fahrzeuge können für die Verladung mit einer Seilwinde geprüft werden."]] : [["What information do you need?", "Contact name, phone number, email, vehicle make and model, collection and delivery locations, and preferred collection date."], ["Is the preferred date a booking?", "No. It is a preferred collection date for discussion, not a reservation or a fixed delivery promise."], ["Do you provide a fixed delivery time?", "Transport options and timing are confirmed directly for each job. We do not publish a universal pickup or transit-time promise."], ["Can you move a vehicle that does not run?", "Complete non-running vehicles can be considered for winch loading. Suitability depends on the vehicle and is confirmed case by case."]]).map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
    <section className="contact-section section-copper"><div><p className="eyebrow">{de ? "Mit den Details beginnen" : "Start with the details"}</p><h2>{c.quote}</h2><p>{de ? "Nennen Sie uns Route, Fahrzeug und Wunschtermin. Wir melden uns innerhalb von 3 Stunden." : "Share your route, vehicle and preferred collection date. We’ll get back to you within 3 hours to discuss your transport requirements."}</p></div><div className="contact-actions"><Link className="button button-dark" href={`${root}/quote`}>{de ? "Angebot anfragen" : "Request a quote"} <span>↗</span></Link><a className="text-link dark" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp Business <span>↗</span></a></div></section>
  </main><Footer lang={lang} /></div></SiteShell>;
}

export function InnerPage({ type, lang = "en" }: { type: "portfolio" | "quote" | "legal"; lang?: Lang }) {
  const de = lang === "de";
  if (type === "quote") return <SiteShell><Header lang={lang} active="quote" /><main><section className="quote-layout section-light"><div className="quote-intro"><p className="eyebrow">{de ? "Angebot anfragen" : "Get a quote"}</p><h1>{de ? "Was soll transportiert werden?" : "Tell us what needs moving."}</h1><p>{de ? "Nennen Sie uns Fahrzeug, Abhol- und Lieferort sowie Ihren Wunschtermin. Wir melden uns innerhalb von 3 Stunden." : "Share the vehicle, collection and delivery locations, and your preferred collection date. We’ll get back to you within 3 hours to discuss your transport requirements."}</p><div className="quote-side-note"><strong>{de ? "Nicht bereit für das Formular?" : "Not ready for the form?"}</strong><a href={whatsapp} target="_blank" rel="noreferrer">{de ? "Über WhatsApp schreiben ↗" : "Chat on WhatsApp ↗"}</a></div></div><QuoteForm de={de} /></section></main><Footer lang={lang} /></SiteShell>;
  if (type === "legal") return <SiteShell><Header /><main><section className="page-intro section-dark"><p className="eyebrow">Before publication</p><h1>Legal information<br /><em>to be completed.</em></h1><p>The legal business name, registered address, identifiers, email and insurance terms are still open and must be confirmed before launch.</p></section><section className="legal-draft section-light"><div><strong>Required details</strong><span>Legal business name</span><span>Registered address</span><span>Business identifiers</span><span>Contact email</span><span>Insurance coverage, limit and conditions</span></div><div><strong>Publication note</strong><p>This draft intentionally does not invent legal or insurance information. It should be replaced with verified details before the website is published.</p></div></section></main><Footer /></SiteShell>;
  return <SiteShell><Header lang={lang} active="portfolio" /><main><section className="page-intro section-dark"><p className="eyebrow">Portfolio</p><h1>{de ? <>Transportgeschichten,<br /><em>wenn sie bereit sind.</em></> : <>Transport stories,<br /><em>when they’re ready.</em></>}</h1><p>{de ? "Wir wählen echte Transportfotos und Routenfälle für die Veröffentlichung aus. Kundendiskretion und Bildrechte stehen an erster Stelle." : "We are selecting actual transport photographs and route cases for publication. Client discretion and image rights come first."}</p></section><section className="portfolio-empty section-light"><div className="empty-mark">A</div><div><h2>{de ? "Echte Arbeit gehört hierher." : "Real work belongs here."}</h2><p>{de ? "Portfolio-Bilder von @aumorex_trans werden nach Auswahl und Rechteprüfung hinzugefügt. Bis dahin bleiben wir ehrlich: kein synthetischer Nachweis, keine erfundenen Bewertungen, keine fremden Fahrzeuggeschichten." : <>Portfolio images from <strong>@aumorex_trans</strong> will be added after selection and rights review. Until then, we keep this space honest: no synthetic proof, no invented testimonials, no borrowed vehicle stories.</>}</p><a className="text-link" href="https://www.instagram.com/aumorex_trans/" target="_blank" rel="noreferrer">{de ? "Instagram ansehen" : "View Instagram"} <span>↗</span></a></div></section><section className="portfolio-note section-warm"><p className="eyebrow">{de ? "Was wir zeigen werden" : "What we will show"}</p><div className="note-grid"><div><strong>Transport</strong><span>{de ? "Autos aus echten Aufträgen." : "Cars loaded and delivered as part of actual jobs."}</span></div><div><strong>{de ? "Menschen" : "People"}</strong><span>{de ? "Fahrer und Koordination hinter dem Transport." : "Drivers, coordination and the practical details behind the move."}</span></div><div><strong>{de ? "Routen" : "Routes"}</strong><span>{de ? "Ausgewählte europäische Fahrten mit Datum und Kontext." : "Selected European journeys with a clear date and context."}</span></div></div></section></main><Footer lang={lang} /></SiteShell>;
}

function QuoteForm({ de }: { de: boolean }) { const fields = de ? [["Kontaktname", "name", "text"], ["Telefonnummer", "phone", "tel"], ["E-Mail", "email", "email"], ["Unternehmen", "company", "text"], ["Fahrzeugmarke und Modell", "vehicle", "text"], ["Ungefähres Gewicht", "weight", "text"], ["Abholort", "collection", "text"], ["Lieferort", "delivery", "text"], ["Wunschtermin", "date", "date"]] : [["Contact name", "name", "text"], ["Phone number", "phone", "tel"], ["Email", "email", "email"], ["Company", "company", "text"], ["Vehicle make and model", "vehicle", "text"], ["Approximate weight", "weight", "text"], ["Collection location", "collection", "text"], ["Delivery location", "delivery", "text"], ["Preferred collection date", "date", "date"]]; return <form className="quote-form" onSubmit={(e) => e.preventDefault()}><div className="form-status" role="status">{de ? "Das Anfrageziel wird noch eingerichtet. Bitte nutzen Sie vorerst WhatsApp für eine Live-Anfrage." : "The request destination is still being configured. For now, please use WhatsApp for a live enquiry."}</div><div className="form-grid">{fields.map(([label, name, type], i) => <label key={name}>{label} {[3, 5].includes(i) ? <span>(optional)</span> : "*"}<input required={!([3, 5].includes(i))} name={name} type={type} /></label>)}<label>{de ? "Fahrzeug fahrbereit?" : "Does the vehicle run?"}<select name="running"><option>{de ? "Auswählen" : "Select one"}</option><option>{de ? "Ja" : "Yes"}</option><option>{de ? "Nein" : "No"}</option><option>{de ? "Nicht sicher" : "Not sure"}</option></select></label></div><label>{de ? "Zusätzliche Angaben" : "Additional details"}<textarea name="details" rows={5} /></label><label className="check-row"><input type="checkbox" name="flexible" /> <span>{de ? "Meine Termine sind flexibel." : "My dates are flexible."}</span></label><button className="button button-dark" type="submit" disabled>{de ? "Angebot anfragen" : "Request a quote"} <span>↗</span></button><p className="form-footnote">{de ? "Der Wunschtermin dient zur Abstimmung und ist keine Reservierung." : "The preferred date is for collection discussion; it is not a reservation."}</p></form>; }
