"use client";

import Link from "next/link";
import QuoteForm from "./quote-form";
import { useEffect, useState } from "react";
import { AumorexLogo } from "../components/brand/AumorexLogo";
import { AumorexSymbol } from "../components/brand/AumorexSymbol";

const whatsapp = "https://wa.me/40750402452?text=Hello%20AUMOREX%2C%20I%E2%80%99d%20like%20a%20quote%20for%20transporting%20my%20car.";
type Lang = "en" | "de";

function FlagIcon({ country }: { country: "uk" | "de" }) {
  if (country === "de") {
    return <svg className="flag-icon" viewBox="0 0 60 40" aria-hidden="true"><rect width="60" height="13.33" fill="#111" /><rect y="13.33" width="60" height="13.34" fill="#D00" /><rect y="26.67" width="60" height="13.33" fill="#FFCE00" /></svg>;
  }

  return <svg className="flag-icon" viewBox="0 0 60 40" aria-hidden="true"><rect width="60" height="40" fill="#012169" /><path d="M0 0 60 40M60 0 0 40" stroke="#FFF" strokeWidth="9" /><path d="M0 0 60 40M60 0 0 40" stroke="#C8102E" strokeWidth="4" /><path d="M30 0v40M0 20h60" stroke="#FFF" strokeWidth="15" /><path d="M30 0v40M0 20h60" stroke="#C8102E" strokeWidth="9" /></svg>;
}

function LanguageLinks({ className = "", active = "en", enHref = "/", deHref = "/de" }: { className?: string; active?: Lang; enHref?: string; deHref?: string }) {
  const isEnglish = active === "en";
  return <span className={`language ${className}`} aria-label="Language selection"><Link className="flag-link active" href={isEnglish ? deHref : enHref} aria-label={isEnglish ? "Switch to Deutsch" : "Switch to English"} title={isEnglish ? "Deutsch" : "English"}><FlagIcon country={isEnglish ? "uk" : "de"} /></Link></span>;
}

export function Header({ lang = "en", active = "" }: { lang?: Lang; active?: string }) {
  const de = lang === "de";
  const root = de ? "/de" : "";
  const enHref = active === "portfolio" ? "/portfolio" : active === "quote" ? "/quote" : "/";
  const deHref = active === "portfolio" ? "/de/portfolio" : active === "quote" ? "/de/quote" : "/de";
  return <header className="site-header">
    <Link className="brand" href={root || "/"} aria-label="AUMOREX transport home"><AumorexSymbol className="brand-symbol brand-symbol-light" variant="light" interactive aria-label="AUMOREX TRANSPORT" width={72} height={72} /><AumorexSymbol className="brand-symbol brand-symbol-dark" variant="monochrome" interactive aria-label="AUMOREX TRANSPORT" width={72} height={72} /></Link>
    <LanguageLinks className="language-mobile" active={lang} enHref={enHref} deHref={deHref} />
    <button className="menu-toggle" aria-expanded="false" aria-controls="site-nav">{de ? "Menü" : "Menu"}</button>
    <nav id="site-nav" className="site-nav" aria-label="Primary navigation"><a href={`${root || "/"}#service`}>Service</a><a href={`${root || "/"}#routes`}>{de ? "Routen" : "Routes"}</a><Link className={active === "portfolio" ? "active" : ""} href={`${root}/portfolio`}>Portfolio</Link><a href={`${root || "/"}#about`}>{de ? "Über uns" : "About"}</a><Link className={`nav-cta ${active === "quote" ? "active" : ""}`} href={`${root}/quote`}>{de ? "Angebot anfragen" : "Get a quote"}</Link><LanguageLinks className="language-desktop" active={lang} enHref={enHref} deHref={deHref} /></nav>
  </header>;
}

export function Footer({ lang = "en" }: { lang?: Lang }) { const de = lang === "de"; const root = de ? "/de" : ""; return <footer className="site-footer"><div className="footer-brand"><AumorexLogo className="footer-logo" variant="light" width={72} height={72} /><span className="sr-only">AUMOREX TRANSPORT</span></div><div className="footer-links"><Link href={`${root}/quote`}>{de ? "Angebot" : "Get a quote"}</Link><Link href={`${root}/portfolio`}>Portfolio</Link><Link href={de ? "/de" : "/legal"}>{de ? "Rechtliche Hinweise" : "Legal information"}</Link></div><div className="footer-meta"><span>{de ? "Dedizierter Autotransport in Westeuropa." : "Dedicated car transport across Western Europe."}</span><span>© AUMOREX transport</span></div></footer>; }

export function SiteShell({ children }: { children: React.ReactNode }) {
  const [top, setTop] = useState(false);
  useEffect(() => { const nav = document.querySelector<HTMLElement>(".site-nav"), toggle = document.querySelector<HTMLButtonElement>(".menu-toggle"), header = document.querySelector<HTMLElement>(".site-header"); const scroll = () => { setTop(scrollY > 420); header?.classList.toggle("is-scrolled", scrollY > 24); }; const click = () => { const open = toggle?.getAttribute("aria-expanded") === "true"; toggle?.setAttribute("aria-expanded", String(!open)); nav?.classList.toggle("open", !open); }; toggle?.addEventListener("click", click); addEventListener("scroll", scroll, { passive: true }); scroll(); const route = document.querySelector<HTMLElement>(".routes-section"); const observer = route && "IntersectionObserver" in window ? new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { route.classList.add("is-visible"); observer?.disconnect(); } }, { threshold: .35 }) : null; if (route && observer) observer.observe(route); return () => { toggle?.removeEventListener("click", click); removeEventListener("scroll", scroll); observer?.disconnect(); }; }, []);
  return <>{children}<button className={`back-to-top ${top ? "is-visible" : ""}`} type="button" aria-label="Back to top" onClick={() => scrollTo({ top: 0, behavior: "smooth" })}><span aria-hidden="true">↑</span><span>Back up</span></button></>;
}

function TypewriterText({ phrases }: { phrases: string[] }) {
  const [phraseIndex, setPhraseIndex] = useState(0);
  const [text, setText] = useState(phrases[0]);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

    const current = phrases[phraseIndex];
    const isComplete = text === current;
    const isEmpty = text.length === 0;
    const delay = isComplete && !isDeleting ? 2200 : isEmpty && isDeleting ? 420 : isDeleting ? 48 : 92;
    const timer = window.setTimeout(() => {
      if (isComplete && !isDeleting) {
        setIsDeleting(true);
        return;
      }
      if (isDeleting && isEmpty) {
        setPhraseIndex((index) => (index + 1) % phrases.length);
        setIsDeleting(false);
        return;
      }
      setText((value) => isDeleting ? value.slice(0, -1) : current.slice(0, value.length + 1));
    }, delay);

    return () => window.clearTimeout(timer);
  }, [isDeleting, phraseIndex, phrases, text]);

  return <span className="typewriter-text" aria-label={phrases[0]}>{text}<span className="typewriter-caret" aria-hidden="true" /></span>;
}

const copy = { en: { hero: ["Dedicated car transport", "Door-to-door vehicle transport", "across Western Europe."], intro: "AUMOREX transports cars between Ireland, the UK, France, Spain, Portugal and other European destinations. Based in Romania, we combine our own fleet with a network of transport partners and direct communication from enquiry to delivery.", response: "Initial replies within 3 hours, 24/7.", service: "Our service", serviceTitle: "A dedicated transport plan for your car.", routes: "Where we operate", routeTitle: "Car transport across", routeWord: "Western Europe", typewriter: ["Western Europe", "your route", "your schedule"], about: "The people behind the transport", quote: "Tell us where your car needs to go." }, de: { hero: ["Dedizierter Autotransport", "Tür-zu-Tür-Fahrzeugtransport", "in Westeuropa."], intro: "AUMOREX transportiert Fahrzeuge zwischen Irland, Großbritannien, Frankreich, Spanien, Portugal und anderen europäischen Zielen. Von Rumänien aus verbinden wir unsere eigene Flotte mit einem Netzwerk von Transportpartnern und direkter Kommunikation — von der Anfrage bis zur Übergabe.", response: "Erste Antwort innerhalb von 3 Stunden, rund um die Uhr.", service: "Unser Service", serviceTitle: "Ein abgestimmter Transportplan für Ihr Fahrzeug.", routes: "Unsere Routen", routeTitle: "Autotransport in", routeWord: "Westeuropa", typewriter: ["Westeuropa", "Ihrer Route", "Ihrem Zeitplan"], about: "Die Menschen hinter dem Transport", quote: "Wohin soll Ihr Fahrzeug?" } };

export function HomePage({ lang = "en" }: { lang?: Lang }) {
  const de = lang === "de", c = copy[lang], root = de ? "/de" : "";
  const routes = de ? ["Irland", "Großbritannien", "Frankreich", "Spanien", "Portugal"] : ["Ireland", "United Kingdom", "France", "Spain", "Portugal"];
  return <SiteShell><div className="homepage"><Header lang={lang} /><main>
    <section className="hero section-dark"><div className="hero-copy"><p className="eyebrow">{c.hero[0]}</p><h1>{c.hero[1]}<br /><em>{c.hero[2]}</em></h1><p className="hero-intro">{c.intro}</p><div className="actions"><Link className="button button-light" href={`${root}/quote`}>{de ? "Angebot anfragen" : "Get a quote"} <span>↗</span></Link><a className="text-link light" href={whatsapp} target="_blank" rel="noreferrer">{de ? "WhatsApp schreiben" : "Chat on WhatsApp"} <span>↗</span></a></div><p className="response-note"><span className="pulse" /> {c.response}</p></div><div className="hero-visual"><span className="visual-coordinate">{de ? "RO — WESTEUROPA" : "RO — WESTERN EUROPE"}</span></div></section>
    <section className="facts section-light"><div className="fact"><strong>01</strong><span>{de ? "Ein Fahrzeug, dediziert" : "Single-car transport"}</span></div><div className="fact"><strong>02</strong><span>{de ? "Tür-zu-Tür-Service" : "Door-to-door service"}</span></div><div className="fact"><strong>03</strong><span>{de ? "Routen in Westeuropa" : "Western European routes"}</span></div></section>
    <section id="service" className="split-section section-light"><div className="section-label">{c.service}</div><div className="section-content"><h2>{c.serviceTitle}</h2><p className="large-copy">{de ? "Ihr Fahrzeug reist auf einem offenen Transporter für ein einzelnes Fahrzeug. Abholung und Lieferung werden direkt mit Ihnen abgestimmt." : "Your car travels on an open transporter dedicated to a single vehicle. We arrange collection and delivery around the confirmed requirements of your job."}</p><p>{de ? "Senden Sie uns Fahrzeug, Route und Wunschtermin. Wir besprechen die verfügbaren Optionen direkt mit Ihnen — ohne automatische Buchung oder unklare Versprechen." : "Share your vehicle, route and preferred collection date. We discuss the available options directly with you — with no automatic booking and no vague promises."}</p><div className="service-columns"><div><h3>{de ? "Fahrzeuganforderungen" : "Vehicle requirements"}</h3><p>{de ? "Unser Standardservice umfasst Fahrzeuge bis 2.200 kg. Fahrzeuge bis 2.500 kg können gegen Aufpreis und nach Bestätigung möglich sein." : "Our standard car transport service accommodates vehicles up to 2,200 kg. Vehicles up to 2,500 kg may be considered at an additional charge, subject to suitable equipment and confirmation."}</p></div><div><h3>{de ? "Fahrzeuge ohne Funktion" : "Non-running vehicles"}</h3><p>{de ? "Komplett fahruntüchtige Fahrzeuge können für die Verladung mit einer Seilwinde geprüft werden. Die Eignung wird im Einzelfall bestätigt." : "Complete non-running vehicles can be considered for winch loading. We confirm suitability case by case, based on the vehicle and loading conditions."}</p></div></div></div></section>
    <section id="routes" className="routes-section section-copper"><div className="section-label">{c.routes}</div><div className="routes-content"><h2>{c.routeTitle}<br /><em className="route-word">{de ? c.routeWord : <TypewriterText phrases={c.typewriter} />}</em></h2><p>{de ? "Unser Hauptkorridor verbindet Irland, Großbritannien, Frankreich, Spanien und Portugal. Andere europäische Ziele sind auf Anfrage möglich." : "Our main routes connect Ireland, the UK, France, Spain and Portugal. If you need transport elsewhere in Europe, ask us about your route."}</p><div className="route-list">{routes.map((r) => <span key={r}>{r}</span>)}<span>{de ? "Übriges Europa" : "Other Europe"} <small>{de ? "auf Anfrage" : "ask us"}</small></span></div></div></section>
    <section className="proof-section section-light"><div className="section-label">{de ? "Echte Transporte" : "Real transport work"}</div><div className="proof-content"><h2>{de ? "Nachvollziehbar. Sorgfältig ausgeführt." : "See how we handle real vehicle transport."}</h2><p>{de ? "Unser Portfolio zeigt ausgewählte echte Transporte und Fahrzeugübergaben. Jedes Beispiel verweist auf den ursprünglichen Beitrag und wird mit Rücksicht auf Veröffentlichungsrechte und Kundendiskretion ausgewählt." : "Our portfolio shows selected real vehicle transports and handovers. Each example links to the original post and is selected with respect for publication rights and client discretion."}</p><Link className="text-link" href={`${root}/portfolio`}>{de ? "Echte Transporte ansehen" : "See real transport examples"} <span>↗</span></Link><div className="proof-note"><strong>{de ? "Verifizierbare Einblicke statt erfundener Bewertungen" : "Proof you can check"}</strong><span>{de ? "Wir zeigen öffentliche Transportdetails und echte Arbeit, anstatt Zitate oder Sterne zu erfinden." : "We show public transport details and real work instead of inventing quotes or star ratings."}</span></div></div></section>
    <section id="about" className="about-section section-dark"><div className="section-label">{c.about}</div><div className="about-content"><h2>{de ? <>Erfahrung am Steuer.<br /><em>Sorgfalt auf der ganzen Strecke.</em></> : <>Experience behind the wheel.<br /><em>A clear process from start to finish.</em></>}</h2><p className="large-copy">{de ? "Unser Hauptfahrer bringt mehr als 25 Jahre Erfahrung im Transport mit. Wir verbinden praktische Routenkenntnis mit sorgfältiger Aufmerksamkeit für Transportdokumente und die Details jedes Auftrags." : "Our principal driver brings more than 25 years of transport experience. We combine practical route knowledge with careful attention to transport documents, loading details and communication throughout the job."}</p></div></section>
    <section className="process-section section-light"><div className="section-label">{de ? "So funktioniert es" : "How it works"}</div><div className="process-list">{(de ? [["Anfrage", "Fahrzeug, Abhol- und Lieferort sowie Wunschtermin mitteilen."], ["Bestätigung", "Wir besprechen Ihre Anforderungen und bestätigen die verfügbaren Optionen."], ["Transport", "Abholung und Lieferung werden nach den bestätigten Auftragsdetails abgestimmt."]] : [["1. Share the details", "Tell us the vehicle, collection and delivery locations, and your preferred collection date."], ["2. Confirm the plan", "We discuss the route and vehicle requirements, then confirm the available transport options directly with you."], ["3. Arrange the move", "Collection and delivery follow the job details agreed with you. The date you request is not a booking until confirmed."]]).map(([title, text]) => <div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section className="faq-section section-warm"><div className="section-label">{de ? "Fragen" : "Questions"}</div><div className="faq-content"><h2>{de ? "Vor Ihrer Angebotsanfrage." : "What to know before requesting a quote."}</h2>{(de ? [["Welche Informationen benötigen Sie?", "Name, Telefonnummer, E-Mail, Fahrzeug, Abhol- und Lieferort sowie der gewünschte Abholtermin."], ["Ist der Wunschtermin eine Buchung?", "Nein. Es handelt sich um einen gewünschten Abholtermin zur Abstimmung, nicht um eine Reservierung."], ["Gibt es eine feste Lieferzeit?", "Transportoptionen und Zeitplanung werden für jeden Auftrag direkt bestätigt."], ["Können Sie ein nicht fahrbereites Fahrzeug transportieren?", "Komplett fahruntüchtige Fahrzeuge können für die Verladung mit einer Seilwinde geprüft werden."]] : [["What information do you need for a quote?", "Your contact details, vehicle make and model, collection and delivery locations, and preferred collection date."], ["Is the preferred date a booking?", "No. It is a preferred collection date for discussion, not a reservation or a fixed delivery promise."], ["Do you provide a fixed delivery time?", "Transport options and timing are confirmed directly for each job. We do not publish a universal pickup or transit-time promise."], ["Can you move a vehicle that does not run?", "Complete non-running vehicles can be considered for winch loading. Suitability depends on the vehicle and is confirmed case by case."]]).map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
    <section className="contact-section section-copper"><div><p className="eyebrow">{de ? "Mit den Details beginnen" : "Start with the details"}</p><h2>{c.quote}</h2><p>{de ? "Nennen Sie uns Route, Fahrzeug und Wunschtermin. Wir melden uns innerhalb von 3 Stunden." : "Tell us the vehicle, route and preferred collection date. We’ll reply within 3 hours to discuss the right transport option for your job."}</p></div><div className="contact-actions"><Link className="button button-dark" href={`${root}/quote`}>{de ? "Angebot anfragen" : "Request a car transport quote"} <span>↗</span></Link><a className="text-link dark" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp Business <span>↗</span></a></div></section>
  </main><Footer lang={lang} /></div></SiteShell>;
}

export function InnerPage({ type, lang = "en" }: { type: "portfolio" | "quote" | "legal"; lang?: Lang }) {
  const de = lang === "de";
  if (type === "quote") return <SiteShell><Header lang={lang} active="quote" /><main><section className="quote-layout section-light"><div className="quote-intro"><p className="eyebrow">{de ? "Angebot anfragen" : "Get a quote"}</p><h1>{de ? "Was soll transportiert werden?" : "Tell us what needs moving."}</h1><p>{de ? "Nennen Sie uns Fahrzeug, Abhol- und Lieferort sowie Ihren Wunschtermin. Wir melden uns innerhalb von 3 Stunden." : "Share the vehicle, collection and delivery locations, and your preferred collection date. We’ll get back to you within 3 hours to discuss your transport requirements."}</p><div className="quote-side-note"><strong>{de ? "Nicht bereit für das Formular?" : "Not ready for the form?"}</strong><a href={whatsapp} target="_blank" rel="noreferrer">{de ? "Über WhatsApp schreiben ↗" : "Chat on WhatsApp ↗"}</a></div></div><QuoteForm de={de} /></section></main><Footer lang={lang} /></SiteShell>;
  if (type === "legal") return <SiteShell><Header /><main><section className="page-intro section-dark"><p className="eyebrow">Before publication</p><h1>Legal information<br /><em>to be completed.</em></h1><p>The legal business name, registered address, identifiers, email and insurance terms are still open and must be confirmed before launch.</p></section><section className="legal-draft section-light"><div><strong>Required details</strong><span>Legal business name</span><span>Registered address</span><span>Business identifiers</span><span>Contact email</span><span>Insurance coverage, limit and conditions</span></div><div><strong>Publication note</strong><p>This draft intentionally does not invent legal or insurance information. It should be replaced with verified details before the website is published.</p></div></section></main><Footer /></SiteShell>;
  const stories = [
    { image: "/portfolio/range-rover-faro-dublin.jpg", title: "Range Rover", route: "Faro → Dublin", detail: de ? "Expresslieferung, direkt gefahren." : "Express delivery, driven direct.", href: "https://www.instagram.com/aumorex_trans/reel/Db75JK5NOJ7/" },
    { image: "/portfolio/mercedes-s63-marbella.jpg", title: "Mercedes-Benz S63 AMG Cabriolet", route: "Germany → Marbella", detail: de ? "Innerhalb von 72 Stunden nach Abholung geliefert." : "Delivered within 72 hours after pickup.", href: "https://www.instagram.com/aumorex_trans/reel/DXM4lUXjUjK/" },
    { image: "/portfolio/g-wagon.jpg", title: "Mercedes-Benz G-Class", route: de ? "Ausgewählte Fahrzeuglieferung" : "Selected vehicle delivery", detail: de ? "Aus dem Instagram-Archiv von AUMOREX." : "From the AUMOREX Instagram archive.", href: "https://www.instagram.com/aumorex_trans/p/DdWG-rkNCQ9/" },
    { image: "/portfolio/lamborghini-portugal.jpg", title: "Lamborghini", route: de ? "Fahrzeugübergabe in Portugal" : "Vehicle handover in Portugal", detail: de ? "Aus dem Instagram-Archiv von AUMOREX." : "From the AUMOREX Instagram archive.", href: "https://www.instagram.com/aumorex_trans/p/DbpzFzRNNAB/" },
  ];
  return <SiteShell><Header lang={lang} active="portfolio" /><main><section className="page-intro section-dark"><p className="eyebrow">Portfolio</p><h1>{de ? <>Transportgeschichten,<br /><em>direkt aus der Praxis.</em></> : <>Transport stories,<br /><em>straight from the road.</em></>}</h1><p>{de ? "Ausgewählte echte Transporte und Fahrzeugübergaben aus dem Instagram-Archiv von @aumorex_trans." : <>Selected real transports and vehicle handovers from the <strong>@aumorex_trans</strong> Instagram archive.</>}</p></section><section className="portfolio-grid section-light" aria-label={de ? "Transportgeschichten" : "Transport stories"}>{stories.map((story) => <article className="portfolio-card" key={story.href}><a className="portfolio-image" href={story.href} target="_blank" rel="noreferrer"><img src={story.image} alt={story.title} /></a><div className="portfolio-card-copy"><p className="eyebrow">{story.route}</p><h2>{story.title}</h2><p>{story.detail}</p><a className="text-link" href={story.href} target="_blank" rel="noreferrer">{de ? "Pe Instagram vezi" : "View on Instagram"} <span>↗</span></a></div></article>)}</section><section className="portfolio-note section-warm"><p className="eyebrow">{de ? "Selecție și context" : "Selection and context"}</p><div className="note-grid"><div><strong>Transport</strong><span>{de ? "Fotografii din livrări și predări reale." : "Photography from real deliveries and handovers."}</span></div><div><strong>{de ? "Sursă" : "Source"}</strong><span>{de ? "Fiecare card trimite la postarea originală." : "Every card links back to the original post."}</span></div><div><strong>{de ? "Discreție" : "Discretion"}</strong><span>{de ? "Adăugăm doar detalii publice și verificabile." : "Only public, verifiable details are added."}</span></div></div></section></main><Footer lang={lang} /></SiteShell>;
}
